BluckBuster/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('user/', include('account.urls', namespace='account')),
    path('movies/', include('cinema.urls', namespace='cinema')),
    path('series/', include('television.urls', namespace='television')),
    path('celebs/', include('people.urls', namespace='people')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'blog.views.custom_404_view'

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('blogs/', views.BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
]    

cinema/urls.py
from django.urls import path
from . import views

app_name = 'cinema'

urlpatterns = [
    path('', views.MovieListView.as_view(), name='movies_list'),
    path('grid/', views.MovieGridView.as_view(), name='movies_grid'),
    path('<int:pk>/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('<int:pk>/', views.MovieDetailView.as_view(), name='movie_detail_by_id'),
    path('search_results/', views.SearchMoviesView.as_view(), name='search_results'),
    path('favorite_movies/add/', views.FavoriteMovieCreateView.as_view(), name='favorite_movie_create'),
]

cinema/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from people.models import Person
from django.contrib.auth.models import User
from datetime import datetime
from django_countries.fields import CountryField


MPAA_CHOICES = [
    ('G', 'General Audiences'),
    ('PG', 'Parental Guidance Suggested'),
    ('PG-13', 'Parents Strongly Cautioned'),
    ('R', 'Restricted'),
    ('NC-17', 'No One 17 and Under Admitted')
]

class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class PlotKeyword(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    imdb_id = models.CharField(max_length=9, unique=True, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    release_year = models.IntegerField(
        validators=[
            MinValueValidator(1900),
            MaxValueValidator(datetime.now().year)
        ],
        blank=True,
        null=True
    )
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    rating = models.DecimalField(max_digits=3, decimal_places=1, validators=[MinValueValidator(1.0), MaxValueValidator(10.0)], blank=True, null=True)
    mpaa_rating = models.CharField(max_length=5, choices=MPAA_CHOICES, blank=True)
    image = models.ImageField(upload_to='movie_images', blank=True, null=True)
    runtime = models.PositiveIntegerField(blank=True, null=True)
    synopsis = models.TextField(blank=True, null=True)
    is_on_slideshow = models.BooleanField(default=False)
    genres = models.ManyToManyField(Genre, blank=True)
    country = CountryField(multiple=True , blank=True)
    cast = models.ManyToManyField('Cast', related_name='movies', blank=True)
    directors = models.ManyToManyField(Person, related_name='directed_movies', blank=True)
    writers = models.ManyToManyField(Person, related_name='written_movies', blank=True)
    plot_keywords = models.ManyToManyField(PlotKeyword, blank=True)
    youtube_trailer_code = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return f'{self.title} - {self.release_year}'
    
    def get_absolute_url(self):
        return reverse('cinema:movie_detail', args=[self.pk, self.slug])
    
    
class Cast(models.Model):
    movie = models.ForeignKey(Movie, related_name='casts', on_delete=models.CASCADE)
    person = models.ForeignKey(Person, related_name='cinema_casts', on_delete=models.CASCADE)
    character_name = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.person} as {self.character_name} in {self.movie.title}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='mcomments')
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)
    liked_users = models.ManyToManyField(User, related_name='liked_comments', blank=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

cinema/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={
                'placeholder': 'Write Comment',
                'class': 'form-style-1',
                'style': 'height: 230px; background-color: #233a50; color: #ffffff; border: 3px solid #0f2133;  border-radius: 3px;',
            })
        }
        
class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }

cinema/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.views import View
from .models import Movie,Comment
from django.contrib import messages
from television.models import TVShow
from people.models import Person
from account.models import FavoriteMovie
from django.db.models import Count
from django_countries import countries
from django.urls import reverse_lazy
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class MovieListView(ListView):
    model = Movie
    context_object_name = 'movies'
    template_name = 'cinema/movies_list.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies_count'] = Movie.objects.aggregate(total=Count('id'))['total']
        return context

class MovieGridView(ListView):
    model = Movie
    context_object_name = 'movies'
    template_name = 'cinema/movies_grid.html'
    paginate_by = 16

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies_count'] = Movie.objects.aggregate(total=Count('id'))['total']
        return context

class MovieDetailView(DetailView):
    model = Movie
    template_name = 'cinema/movie_detail.html'
    slug_url_kwarg = 'slug'
    paginate_by = 20
    form_class = CommentForm

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        slug = self.kwargs.get('slug')
        if pk is not None:
            return get_object_or_404(Movie, pk=pk)
        elif slug is not None:
            return get_object_or_404(Movie, slug=slug)
        else:
            return None

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        if object is None:
            return super().get(request, *args, **kwargs)
        else:
            canonical_url = reverse('cinema:movie_detail', kwargs={
                'pk': object.pk,
                'slug': object.slug,
            })
            requested_url = request.path_info

            if requested_url != canonical_url:
                return redirect(canonical_url)

            comments = Comment.objects.filter(movie=object).order_by('-created')
            comment_count = comments.count()
            is_favorite = False
            if request.user.is_authenticated:
                favorite_movies = FavoriteMovie.objects.filter(user=request.user, movie=object)
                is_favorite = favorite_movies.exists()
                

            paginator = Paginator(comments, self.paginate_by)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            context = {
                'movie': object,
                'genres': object.genres.all(),
                'cast': object.casts.all(),
                'directors': object.directors.all(),
                'writers': object.writers.all(),
                'plotkeys': object.plot_keywords.all(),
                'countries': [countries.name(code) for code in object.country],
                'comments': page_obj,  # Pass the paginated comments to the template
                'comment_count': comment_count,
                'comment_form': CommentForm(),  # Add the comment form to the context
                'is_favorite': is_favorite,
            }

            return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        object = self.get_object()
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.movie = object
            new_comment.save()
            messages.success(request, 'Your comment was submitted successfully.', 'success')
        else:
            messages.error(request, 'There was an error submitting your comment.', 'error')
        return redirect('cinema:movie_detail', pk=object.pk, slug=object.slug)


        
class SearchMoviesView(View):

    def get(self, request):
        return render(request, 'cinema/search_results.html')
    
    def post(self, request):
      searched = request.POST.get('searched', '')
      media_type = request.POST.get('media_type', 'all')
      if not searched:  # Empty search query
        context = {'searched': searched, 'movies': [], 'series': [], 'celebs': [], 'media_type': media_type}
        return render(request, 'cinema/search_results.html', context)

      if media_type == 'movies':
        movies = Movie.objects.filter(title__icontains=searched)
        series = []
        celebs = []
      elif media_type == 'series':
        movies = []
        series = TVShow.objects.filter(title__icontains=searched)
        celebs = []
      elif media_type == 'celebs':
        movies = []
        series = []
        celebs = Person.objects.filter(name__icontains=searched)
      else:
        movies = Movie.objects.filter(title__icontains=searched)
        series = TVShow.objects.filter(title__icontains=searched)
        celebs = Person.objects.filter(name__icontains=searched)
        media_type = 'all'
      context = {'searched': searched, 'movies': movies, 'series': series, 'celebs': celebs, 'media_type': media_type}
      return render(request, 'cinema/search_results.html', context)




class FavoriteMovieCreateView(LoginRequiredMixin, View):
    def get(self, request):
        movie_id = request.GET.get('movie_id')
        movie = Movie.objects.get(id=movie_id)
        movie_in_favorites = FavoriteMovie.objects.filter(user=request.user, movie=movie).exists()

        if movie_in_favorites:
            return redirect('cinema:movie_detail', pk=movie.pk, slug=movie.slug)  # Redirect back to the movie detail page

        favorite_movie = FavoriteMovie(user=request.user, movie=movie)
        favorite_movie.save()
        return redirect('cinema:movie_detail', pk=movie.pk, slug=movie.slug)

cinema/templates/cinema/movies_grid.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1> movie listing - grid</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="page-single">
	<div class="container">
		<div class="row ipad-width">

			<!-- Movies list part -->
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p>Found <span>{{ movies_count }} movies</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="{% url 'cinema:movies_list' %}" class="list"><i class="ion-ios-list-outline "></i></a>
					<a  href="{% url 'cinema:movies_grid' %}" class="grid"><i class="ion-grid active"></i></a>
				</div>
				<div class="flex-wrap-movielist">
						{% for movie in movies %}
						<div class="movie-item-style-2 movie-item-style-1">
							<img src="{{ movie.image.url }}"alt="">
							<div class="hvr-inner">
	            				<a  href="{{ movie.get_absolute_url }}"> Read more <i class="ion-android-arrow-dropright"></i> </a>
	            			</div>
							<div class="mv-item-infor">
								<h6><a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a></h6>
								<p class="rate"><i class="ion-android-star"></i><span>{{ movie.rating}}</span> /10</p>
							</div>
						</div>	
						{% endfor %}				
				</div>		
				<ul class="pagination">
					{% if page_obj.has_previous %}
						<a href="?page=1">&laquo; first &nbsp; </a>
						<li class="icon-prev"><a href="?page={{ page_obj.previous_page_number }}"><i class="ion-ios-arrow-left"></i></a></li>
					{% else %}
						<li class="icon-prev disabled"><span><i class="ion-ios-arrow-left"></i></span></li>
					{% endif %}
				
					{% for page_num in page_obj.paginator.page_range %}
						{% if page_obj.number == page_num %}
							<li class="active"><a>{{ page_num }} <span class="sr-only">(current)</span></a></li>
						{% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
							<li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
						{% endif %}
					{% endfor %}
				
				
					{% if page_obj.has_next %}
						<li class="icon-next"><a href="?page={{ page_obj.next_page_number }}"><i class="ion-ios-arrow-right"></i></a></li>
						<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					{% else %}
						<li class="icon-next disabled"><span><i class="ion-ios-arrow-right"></i></span></li>
					{% endif %}
				</ul>
			</div>
			<!-- end of Movies list part -->

			<!-- Side bar -->			
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="sidebar">

					<!-- Search Bar-2 list part in side bar -->	
					<div class="searh-form">
						<h4 class="sb-title">Search for movie</h4>
						<form class="form-style-1" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Movie name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Genres & Subgenres</label>
									<div class="group-ip">
										<select
											name="skills" multiple="" class="ui fluid dropdown">
											<option value="">Enter to filter genres</option>
											<option value="Action1">Action 1</option>
					                        <option value="Action2">Action 2</option>
					                        <option value="Action3">Action 3</option>
					                        <option value="Action4">Action 4</option>
					                        <option value="Action5">Action 5</option>
										</select>
									</div>	
								</div>
								<div class="col-md-12 form-it">
									<label>Rating Range</label>
									<select>
									  <option value="range">-- Select the rating range below --</option>
									  <option value="saab">-- Select the rating range below --</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Release Year</label>
									<div class="row">
										<div class="col-md-6">
											<select>
											  <option value="range">From</option>
											  <option value="number">10</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
											  <option value="range">To</option>
											  <option value="number">20</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<!-- end of Search Bar-2 list part in side bar -->	

					<!-- Featured Celebrities list part in side bar -->	
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava1.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava2.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava3.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava4.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
					<!-- end of Featured Celebrities list part -->	

				</div>
			</div>
			<!-- end of Side bar -->
			
		</div>
	</div>
</div>
{% endblock %}

cinema/templates/cinema/movies_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- List Page Header -->
<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1> movie listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END of List Page Header -->

<div class="page-single movie_list">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p>Found <span>{{ movies_count }} movies</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="{% url 'cinema:movies_list' %}" class="list"><i class="ion-ios-list-outline active"></i></a>
					<a href="{% url 'cinema:movies_grid' %}" class="grid"><i class="ion-grid"></i></a>
				</div>

			<!-- Displaying a list of movies with their details and cast members-->
				{% for movie in movies %}
				<div class="movie-item-style-2">
					<img src="{{ movie.image.url }}">
			
					<div class="mv-item-infor">
						<h6>
							<a href="{{ movie.get_absolute_url }}">
								{{ movie.title }}
								<span>&nbsp;{{ movie.release_year }}</span>
							</a>
						</h6>
			
						<p class="rate">
							<i class="ion-android-star"></i>
							<span>{{ movie.rating }}</span> /10
						</p>
			
						<p class="describe">
							{{ movie.synopsis|truncatechars_html:249}}
						</p>
			
						<p class="run-time">
							Run Time: {{ movie.runtime }} min.
							<span>MMPA: {{ movie.mpaa_rating }}</span>
							<span>Release: {{ movie.release_year }}</span>
						</p>
			
						<p> Director:
							{% for director in movie.directors.all %}
								{% if forloop.first %}
									<a href="{{ director.get_absolute_url }}">
										{{ director.name }}
									</a>
								{% else %}
									, <a href="{{ director.get_absolute_url }}">
										{{ director.name }}
									</a>
								{% endif %}
							{% endfor %}
						</p>
			
						<p> Stars:
							{% for cast_obj in movie.casts.all|slice:":3" %}
								{% if forloop.first %}
									<a href="{{ cast_obj.person.get_absolute_url }}">
										{{ cast_obj.person.name }}
									</a>
								{% else %}
									, <a href="{{ cast_obj.person.get_absolute_url }}">
										{{ cast_obj.person.name }}
									</a>
								{% endif %}
							{% endfor %}
						</p>
					</div>
				</div>
				{% endfor %}
			<!-- End of Displaying a list of Movies with their details and cast members-->		
			

			<!-- pagination-->
				<ul class="pagination">

					{% if page_obj.has_previous %}
						<a href="?page=1">&laquo; first &nbsp; </a>
						<li class="icon-prev"><a href="?page={{ page_obj.previous_page_number }}"><i class="ion-ios-arrow-left"></i></a></li>
					{% else %}
						<li class="icon-prev disabled"><span><i class="ion-ios-arrow-left"></i></span></li>
					{% endif %}
				
					{% for page_num in page_obj.paginator.page_range %}
						{% if page_obj.number == page_num %}
							<li class="active"><a>{{ page_num }} <span class="sr-only">(current)</span></a></li>
						{% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
							<li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
						{% endif %}
					{% endfor %}
				
				
					{% if page_obj.has_next %}
						<li class="icon-next"><a href="?page={{ page_obj.next_page_number }}"><i class="ion-ios-arrow-right"></i></a></li>
						<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					{% else %}
						<li class="icon-next disabled"><span><i class="ion-ios-arrow-right"></i></span></li>

					{% endif %}
				</ul>
			<!-- end of pagination-->
			</div>

			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="sidebar">
					<div class="searh-form">
						<h4 class="sb-title">Search for movie</h4>
						<form class="form-style-1" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Movie name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Genres</label>
									<div class="group-ip">
										<select
											name="skills" multiple="" class="ui fluid dropdown">
											<option value="">Enter to filter genres</option>
											<option value="Action1">Action 1</option>
					                        <option value="Action2">Action 2</option>
					                        <option value="Action3">Action 3</option>
					                        <option value="Action4">Action 4</option>
					                        <option value="Action5">Action 5</option>
										</select>
									</div>	
								</div>
								<div class="col-md-12 form-it">
									<label>Rating Range</label>
									<select>
									  <option value="range">-- Select the rating range below --</option>
									  <option value="saab">-- Select the rating range below --</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Release Year</label>
									<div class="row">
										<div class="col-md-6">
											<select>
											  <option value="range">From</option>
											  <option value="number">10</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
											  <option value="range">To</option>
											  <option value="number">20</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava1.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava2.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava3.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava4.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>

{% endblock %}