BluckBuster/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('user/', include('account.urls', namespace='account')),
    path('movies/', include('cinema.urls', namespace='cinema')),
    path('series/', include('television.urls', namespace='television')),
    path('celebs/', include('people.urls', namespace='people')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'blog.views.custom_404_view'

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('blogs/', views.BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
]    

people/urls.py
from django.urls import path
from . import views

app_name = 'people'

urlpatterns = [
    path('', views.CelebListView.as_view(), name='celeb_list'),
    path('<int:pk>/', views.CelebDetailView.as_view(), name='celeb_detail'),
    path('grid/', views.CelebGridView.as_view(), name='celeb_grid'),
]

people/models.py
from django.db import models
from django.urls import reverse
from time import timezone
from django_countries.fields import CountryField

JOB_CHOICES = [
    ('actor', 'Actor'),
    ('writer', 'Writer'),
    ('director', 'Director'),
]

class Person(models.Model):
    name = models.CharField(max_length=255)
    full_name = models.CharField(max_length=255, blank=True,null=True)
    job = models.CharField(max_length=10, choices=JOB_CHOICES, blank=True,null=True)
    country = CountryField(blank=True)
    birthday = models.DateField(blank=True,null=True)
    bio = models.TextField(blank=True,null=True)
    photo = models.ImageField(upload_to='people/photos', blank=True,null=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('people:celeb_detail', args=[self.pk])

people/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Person
from cinema.models import Movie
from television.models import TVShow
from django.db.models import Count
from django_countries import countries

class CelebListView(ListView):
    model = Person
    context_object_name = 'celebs'
    template_name = 'people/celebs_list.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['celebs_count'] = Person.objects.aggregate(total=Count('id'))['total']
        return context

class CelebGridView(ListView):
    model = Person
    context_object_name = 'celebs'
    template_name = 'people/celebs_grid.html'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['celebs_count'] = Person.objects.aggregate(total=Count('id'))['total']
        
        return context    

class CelebDetailView(DetailView):
    model = Person
    template_name = 'people/celeb_detail.html'
    context_object_name = 'celeb'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        celeb = self.get_object()
        movies_directed = Movie.objects.filter(directors=celeb)
        movies_written = Movie.objects.filter(writers=celeb)
        movies_cast = Movie.objects.filter(casts__person=celeb)
        movies = set(list(movies_directed) + list(movies_written) + list(movies_cast))
        
        series_written = TVShow.objects.filter(writers=celeb)
        series_cast = TVShow.objects.filter(casts__person=celeb)
        series = set(list(series_written) + list(series_cast))

        context['movies'] = movies
        context['series'] = series
        context['countries'] = [celeb.country.name] 
        return context

people/templates/people/celeb_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero hero3">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- <h1> movie listing - list</h1>
				<ul class="breadcumb">
					<li class="active"><a href="#">Home</a></li>
					<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>
<!-- celebrity single section-->

<div class="page-single movie-single cebleb-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="mv-ceb">
                    {% if celeb.photo %}
                        <img src="{{ celeb.photo.url }}" alt="">
                    {% else %}
                        <img src="{% static 'images/uploads/user-img.png' %}" alt="" width="70" height="70">
                    {% endif %}
				</div>
			</div>
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="movie-single-ct">
					<h1 class="bd-hd">{{ celeb.name }}</h1>
					<p class="ceb-single" >{{ celeb.job|capfirst }}</p>
					<div class="social-link cebsingle-socail">
						<a href="#"><i class="ion-social-facebook"></i></a>
						<a href="#"><i class="ion-social-twitter"></i></a>
						<a href="#"><i class="ion-social-googleplus"></i></a>
						<a href="#"><i class="ion-social-linkedin"></i></a>
					</div>
					<div class="movie-tabs">
						<!-- Displaying a list of movies who-->
						<div class="tabs">
							<ul class="tab-links tabs-mv">
								<li class="active"><a href="#overviewceb">Overview</a></li>
								<li><a href="#filmography">filmography</a></li>                        
							</ul>
						    <div class="tab-content">
						        <div id="overviewceb" class="tab active">
						            <div class="row">
						            	<div class="col-md-8 col-sm-12 col-xs-12">
						            		<p>{{ celeb.bio }}</p>
											<div class="title-hd-sm">
												<h4>filmography</h4>
												<a href="#" class="time">Full Filmography<i class="ion-ios-arrow-right"></i></a>
											</div>
											<!-- movie cast -->
											<div class="mvcast-item">
												{% if movies %}
													<h2>Movies</h2>
													{% for movie in movies %}
														<div class="cast-it">
															<div class="cast-left cebleb-film">
																<img src="{{ movie.image.url }}" alt="{{ movie.title }}" width="55" height="77">
																<div>
																	<a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
																	<p class="time">
																		{% for cast in movie.casts.all %}
																			{% if cast.person == celeb %}
																				{{ cast.character_name }}
																			{% endif %}
																		{% endfor %}
																	</p>
																</div>
															</div>
															<p>{{ movie.release_date.year }}</p>
														</div>
													{% endfor %}
												{% else %}
													<p>No movies found for this person.</p>
												{% endif %}

												{% if series %}
													<h2>Series</h2>
													{% for serie in series %}
														<div class="cast-it">
															<div class="cast-left cebleb-film">
																<img src="{{ serie.image.url }}" width="55" height="77">
																<div>
																	<a href="{{ serie.get_absolute_url }}">{{ serie.title }}</a>
																	<p class="time">
																		{% for cast in serie.casts.all %}
																			{% if cast.person == celeb %}
																				{{ cast.character_name }}
																			{% endif %}
																		{% endfor %}
																	</p>
																</div>
															</div>
															<p>{{ serie.status|capfirst }}</p>
														</div>
													{% endfor %}
												{% else %}
													<p>No series found for this person.</p>
												{% endif %}
											</div>
											<!-- end of movie cast -->
						            	</div>
										<!-- Celebrity Info -->
						            	<div class="col-md-4 col-xs-12 col-sm-12">
						            		<div class="sb-it">
						            			<h6>Fullname:  </h6>
						            			<p>{{ celeb.name }}</p>
						            		</div>
						            		<div class="sb-it">
						            			<h6>Date of Birth: </h6>
						            			<p>{{ celeb.birthday|date:'F j, Y' }}</p>
						            		</div>
                                            <div class="sb-it">
						            			<h6>Country:</h6>
                                                <p>
                                                    {% for country in countries %}
                                                            <a href="#">{{ country }}</a>
                                                    {% endfor %}  
                                                </p>  
						            		</div>
						            		<div class="sb-it">
						            			<h6>Keywords:</h6>
						            			<p class="tags">
						            				<span class="time"><a href="#">jackman</a></span>
						            			</p>
						            		</div>
						            	</div>
										<!-- End of Celebrity Info -->

						            </div>
						        </div>
					       	 	<div id="filmography" class="tab">
						        	<div class="row">
						            	<div class="rv-hd">
						            		<div>
						            			<h2>Projects of {{ celeb.name }} :</h2>
						            		</div>
										
						            	</div>
										<!-- movie cast -->
										<div class="mvcast-item">											
											{% if movies %}
												<h2>Movies</h2>
												{% for movie in movies %}
													<div class="cast-it">
														<div class="cast-left cebleb-film">
															<img src="{{ movie.image.url }}" alt="{{ movie.title }}" width="55" height="77">
															<div>
																<a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
																<p class="time">
																{% for cast in movie.casts.all %}
																	{% if cast.person == celeb %}
																		{{ cast.character_name }}
																	{% endif %}
																{% endfor %}
																</p>
															</div>
														</div>
														<p>{{ movie.release_date.year }}</p>
													</div>
												{% endfor %}
											{% else %}
												<p>No movies found for this person.</p>
											{% endif %}

											{% if series %}
											<h2>Series</h2>
											{% for serie in series %}
												<div class="cast-it">
													<div class="cast-left cebleb-film">
														<img src="{{ serie.image.url }}" width="55" height="77">
														<div>
															<a href="{{ serie.get_absolute_url }}">{{ serie.title }}</a>
															<p class="time">
															{% for cast in serie.casts.all %}
																{% if cast.person == celeb %}
																	{{ cast.character_name }}
																{% endif %}
															{% endfor %}
															</p>
														</div>
													</div>
													<p>{{ serie.status|capfirst}}</p>
												</div>
											{% endfor %}
											{% else %}
												<p>No series found for this person.</p>
											{% endif %}

										</div>
						            </div>
					       	 	</div>
						    </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>
<!-- celebrity single section-->
{% endblock %}

people/templates/people/celebs_grid.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>celebrity listing - grid</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> celebrity listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- celebrity grid v2 section-->
<div class="page-single">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p class="pad-change">Found <span>{{ celebs_count }}</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="{% url 'people:celeb_list' %}" class="list"><i class="ion-ios-list-outline "></i></a>
					<a  href="{% url 'people:celeb_grid' %}" class="grid"><i class="ion-grid active"></i></a>
				</div>
				<div class="row">
					{% for celeb in celebs %}
						<div class="col-md-4">
							<div class="ceb-item-style-2">
                                {% if celeb.photo %}
                                    <img src="{{ celeb.photo.url }}" alt=""width="70" height="90">
                                {% else %}
                                    <img src="{% static 'images/uploads/user-img.png' %}" alt="" width="70" height="70">
                                {% endif %}
								<div class="ceb-infor">
									<h2><a href="{{ celeb.get_absolute_url }}">{{ celeb.name }}</a></h2>
									<span>{{ celeb.job }}</span>
								</div>
							</div>
						</div>
					{% endfor %}					
				</div>
				<ul class="pagination">
					{% if page_obj.has_previous %}
						<a href="?page=1">&laquo; first &nbsp; </a>
						<li class="icon-prev"><a href="?page={{ page_obj.previous_page_number }}"><i class="ion-ios-arrow-left"></i></a></li>
					{% else %}
						<li class="icon-prev disabled"><span><i class="ion-ios-arrow-left"></i></span></li>
					{% endif %}
				
					{% for page_num in page_obj.paginator.page_range %}
						{% if page_obj.number == page_num %}
							<li class="active"><a>{{ page_num }} <span class="sr-only">(current)</span></a></li>
						{% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
							<li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
						{% endif %}
					{% endfor %}
				
				
					{% if page_obj.has_next %}
						<li class="icon-next"><a href="?page={{ page_obj.next_page_number }}"><i class="ion-ios-arrow-right"></i></a></li>
						<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					{% else %}
						<li class="icon-next disabled"><span><i class="ion-ios-arrow-right"></i></span></li>
					{% endif %}
				</ul>
			</div>
			<div class="col-md-3 col-xs-12 col-sm-12">
				<div class="sidebar">
						<div class="searh-form">
						<h4 class="sb-title">Search celebrity</h4>
						<form class="form-style-1 celebrity-form" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Celebrity name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Celebrity Letter</label>
									<select>
									  <option value="range">A</option>
									  <option value="saab">B</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Category</label>
									<select>
									  <option value="range">Actress</option>
									  <option value="saab">Others</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Year of birth</label>
									<div class="row">
										<div class="col-md-6">
											<select>
											  <option value="range">1970</option>
											  <option value="number">Other</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
											  <option value="range">1990</option>
											  <option value="number">others</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava1.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava2.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava3.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava4.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end of celebrity grid v2 section-->
{% endblock %}

people/templates/people/celebs_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero hero3">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>celebrity listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> celebrity listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- celebrity list section-->
<div class="page-single">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p class="pad-change">Found <span>{{ celebs_count }} celebrities</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="{% url 'people:celeb_list' %}" class="list"><i class="ion-ios-list-outline active"></i></a>
					<a  href="{% url 'people:celeb_grid' %}" class="grid"><i class="ion-grid "></i></a>
				</div>
				<!-- Displaying a list of CAST-->	
				{% for celeb in celebs %}
				<div class="row">
					<div class="col-md-12">
						<div class="ceb-item-style-2">
                            {% if celeb.photo %}
                                <img src="{{ celeb.photo.url }}" alt="" width="70" height="70">
                            {% else %}
                                <img src="{% static 'images/uploads/user-img.png' %}" alt="" width="70" height="70">
                            {% endif %}
							<div class="ceb-infor">
								<h2><a href="{{ celeb.get_absolute_url }}">{{ celeb.name }}</a></h2>
								<span>{{ celeb.job }}</span>
								<p>{{ celeb.bio|truncatechars_html:320 }}. </p>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				<!-- End of Displaying a list of CAST-->
				<ul class="pagination">
					{% if page_obj.has_previous %}
						<a href="?page=1">&laquo; first &nbsp; </a>
						<li class="icon-prev"><a href="?page={{ page_obj.previous_page_number }}"><i class="ion-ios-arrow-left"></i></a></li>
					{% else %}
						<li class="icon-prev disabled"><span><i class="ion-ios-arrow-left"></i></span></li>
					{% endif %}
				
					{% for page_num in page_obj.paginator.page_range %}
						{% if page_obj.number == page_num %}
							<li class="active"><a>{{ page_num }} <span class="sr-only">(current)</span></a></li>
						{% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
							<li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
						{% endif %}
					{% endfor %}
				
				
					{% if page_obj.has_next %}
						<li class="icon-next"><a href="?page={{ page_obj.next_page_number }}"><i class="ion-ios-arrow-right"></i></a></li>
						<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					{% else %}
						<li class="icon-next disabled"><span><i class="ion-ios-arrow-right"></i></span></li>
					{% endif %}
				</ul>
			</div>
			<div class="col-md-3 col-xs-12 col-sm-12">
				<div class="sidebar">
						<div class="searh-form">
						<h4 class="sb-title">Search celebrity</h4>
						<form class="form-style-1 celebrity-form" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Celebrity name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Celebrity Letter</label>
									<select>
									  <option value="range">A</option>
									  <option value="saab">B</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Category</label>
									<select>
									  <option value="range">Actress</option>
									  <option value="saab">Others</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Year of birth</label>
									<div class="row">
										<div class="col-md-6">
											<select>
											  <option value="range">1970</option>
											  <option value="number">Other</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
											  <option value="range">1990</option>
											  <option value="number">others</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava1.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava2.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava3.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava4.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end of celebrity list section-->
{% endblock %}