BluckBuster/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('user/', include('account.urls', namespace='account')),
    path('movies/', include('cinema.urls', namespace='cinema')),
    path('series/', include('television.urls', namespace='television')),
    path('celebs/', include('people.urls', namespace='people')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'blog.views.custom_404_view'

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('blogs/', views.BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
]    

television/urls.py
from django.urls import path
from . import views

app_name = 'television'

urlpatterns = [
    path('', views.SerieListView.as_view(), name='series_list'),
    path('grid/', views.SerieGridView.as_view(), name='series_grid'),
    path('<int:pk>/<slug:slug>/', views.SerieDetailView.as_view(), name='serie_detail'),
    path('<int:pk>/', views.SerieDetailView.as_view(), name='serie_detail_by_id'),
    path('favorite_series/add/', views.FavoriteTVShowCreateView.as_view(), name='favorite_serie_create')
]

television/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from cinema.models import Genre,PlotKeyword
from people.models import Person
from datetime import datetime
from django_countries.fields import CountryField
from django.contrib.auth.models import User


class Network(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


MPAA_CHOICES = [
    ('TV-Y', 'Suitable for all Children'),
    ('TV-Y7', 'Suitable for Children aged 7 and up'),
    ('TV-G', 'Suitable for all ages)'),
    ('TV-PG', 'Parental Guidance Suggested'),
    ('TV-14', 'Parents Strongly Cautioned'),
    ('TV-MA', 'Mature Audiences Only')
]


class TVShow(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, blank=True, null=True)
    release_year = models.IntegerField(
        validators=[
            MinValueValidator(1900),
            MaxValueValidator(datetime.now().year)
        ],
        blank=True,
        null=True
    )
    finish_year = models.IntegerField(
        validators=[
            MinValueValidator(1900),
            MaxValueValidator(datetime.now().year)
        ],
        blank=True,
        null=True
    )    
    imdb_id = models.CharField(max_length=9, unique=True, blank=True, null=True)
    network = models.ForeignKey(Network, on_delete=models.CASCADE, null=True, blank=True)
    mpaa_rating = models.CharField(max_length=5, choices=MPAA_CHOICES, blank=True, null=True)
    image = models.ImageField(upload_to='tvshow_images', blank=True, null=True)
    rating = models.DecimalField(max_digits=3, decimal_places=1, validators=[MinValueValidator(1.0), MaxValueValidator(10.0)], blank=True, null=True)
    runtime = models.PositiveIntegerField(blank=True, null=True)
    synopsis = models.TextField(blank=True, null=True)
    is_on_slideshow = models.BooleanField(default=False)
    num_seasons = models.PositiveIntegerField(blank=True, null=True)
    status = models.CharField(max_length=50, choices=[('now playing', 'Now Playing'), ('ended', 'Ended')],blank=True)
    country = CountryField(multiple=True , blank=True)
    genres = models.ManyToManyField(Genre,blank=True)
    plot_keywords = models.ManyToManyField(PlotKeyword,blank=True)
    cast = models.ManyToManyField('Cast', related_name='movies', blank=True)
    writers = models.ManyToManyField(Person, related_name='written_tvshow', blank=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('television:serie_detail', args=[self.pk, self.slug])
    
    
class Cast(models.Model):
    tvshow = models.ForeignKey(TVShow, related_name='casts', on_delete=models.CASCADE)
    person = models.ForeignKey(Person, related_name='television_casts', on_delete=models.CASCADE)
    character_name = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.person.name} ({self.character_name}) in {self.tvshow.title}'
    
class Season(models.Model):
    season_number = models.PositiveIntegerField()
    image = models.ImageField(upload_to='season_images')
    tv_show = models.ForeignKey(TVShow, on_delete=models.CASCADE, related_name='seasons')
    episode_number = models.PositiveIntegerField()

    class Meta:
        ordering = ['tv_show__title', 'season_number']
        
    def __str__(self):
        return f'Season {self.season_number} - {self.tv_show.title}'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='series_ucomments')
    tvshow = models.ForeignKey(TVShow, on_delete=models.CASCADE, related_name='series_mcomments')
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)
    liked_users = models.ManyToManyField(User, related_name='series_liked_comments', blank=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

television/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={
                'placeholder': 'Write Comment',
                'class': 'form-style-1',
                'style': 'height: 230px; background-color: #233a50; color: #ffffff; border: 3px solid #0f2133;  border-radius: 3px;',
            })
        }
        
class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }

television/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.views import View
from .models import TVShow,Season,Comment
from account.models import FavoriteTVShow
from .forms import CommentForm
from django.db.models import Count
from django_countries import countries
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

class SerieListView(ListView):
    model = TVShow
    context_object_name = 'series'
    template_name = 'television/series_list.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['series_count'] = TVShow.objects.aggregate(total=Count('id'))['total']
        return context    

class SerieGridView(ListView):
    model = TVShow
    context_object_name = 'series'
    template_name = 'television/series_grid.html'
    paginate_by = 8
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['series_count'] = TVShow.objects.aggregate(total=Count('id'))['total']
        return context    
    
class SerieDetailView(DetailView):
    model = TVShow
    template_name = 'television/serie_detail.html'
    slug_url_kwarg = 'slug'
    paginate_by = 20
    form_class = CommentForm

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        slug = self.kwargs.get('slug')
        if pk is not None:
            return get_object_or_404(TVShow, pk=pk)
        elif slug is not None:
            return get_object_or_404(TVShow, slug=slug)
        else:
            return None

    def get(self, request, *args, **kwargs):
        
        object = self.get_object()

        if object is None:
            return super().get(request, *args, **kwargs)
        else:
            canonical_url = reverse('television:serie_detail', kwargs={
                'pk': object.pk,
                'slug': object.slug,
            })
            requested_url = request.path_info

            if requested_url != canonical_url:
                return redirect(canonical_url)

            comments = Comment.objects.filter(tvshow=object).order_by('-created')
            comment_count = comments.count()
            is_favorite = False
            if request.user.is_authenticated:
                favorite_series = FavoriteTVShow.objects.filter(user=request.user, tvshow=object)
                is_favorite = favorite_series.exists()

            paginator = Paginator(comments, self.paginate_by)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            context = {
                'serie': object,
                'genres' : object.genres.all(),
                'seasons': Season.objects.filter(tv_show=object),
                'cast' : object.casts.all(),
                'writers' : object.writers.all(),
                'plotkeys' : object.plot_keywords.all(),
                'countries' : [countries.name(code) for code in object.country],
                'comments': page_obj,
                'comment_count': comment_count,
                'is_favorite' : is_favorite,
                }

            return render(request, self.template_name, context)
        
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        object = self.get_object()
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.tvshow = object
            new_comment.save()
            messages.success(request, 'Your comment was submitted successfully.', 'success')
        else:
            messages.error(request, 'There was an error submitting your comment.', 'error')
        return redirect('television:serie_detail', pk=object.pk, slug=object.slug)    
    
class FavoriteTVShowCreateView(LoginRequiredMixin, View):
    def get(self, request):
        tvshow_id = request.GET.get('tvshow_id')
        tvshow = TVShow.objects.get(id=tvshow_id)
        tvshow_in_favorites = FavoriteTVShow.objects.filter(user=request.user, tvshow=tvshow).exists()

        if tvshow_in_favorites:
            return redirect('television:serie_detail', pk=tvshow.pk, slug=tvshow.slug)

        favorite_tvshow = FavoriteTVShow(user=request.user, tvshow=tvshow)
        favorite_tvshow.save()
        return redirect('television:serie_detail', pk=tvshow.pk, slug=tvshow.slug)

television/templates/television/series_grid.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="hero sr-single-hero sr-single">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1> serie listing - grid</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> serie listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p>Found <span>{{ series_count }} movies</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="{% url 'television:series_list' %}" class="list"><i class="ion-ios-list-outline "></i></a>
					<a  href="{% url 'television:series_grid' %}" class="grid"><i class="ion-grid active"></i></a>
				</div>
				<div class="flex-wrap-movielist">
						{% for serie in series %}
						<div class="movie-item-style-2 movie-item-style-1">
							<img src="{{ serie.image.url }}"alt="">
							<div class="hvr-inner">
	            				<a  href="{{ serie.get_absolute_url }}"> Read more <i class="ion-android-arrow-dropright"></i> </a>
	            			</div>
							<div class="mv-item-infor">
								<h6><a href="{{ serie.get_absolute_url }}">{{ serietitle }}</a></h6>
								<p class="rate"><i class="ion-android-star"></i><span>{{ serie.rating}}</span> /10</p>
							</div>
						</div>	
						{% endfor %}				
				</div>		
				<ul class="pagination">
					{% if page_obj.has_previous %}
						<a href="?page=1">&laquo; first &nbsp; </a>
						<li class="icon-prev"><a href="?page={{ page_obj.previous_page_number }}"><i class="ion-ios-arrow-left"></i></a></li>
					{% else %}
						<li class="icon-prev disabled"><span><i class="ion-ios-arrow-left"></i></span></li>
					{% endif %}
				
					{% for page_num in page_obj.paginator.page_range %}
						{% if page_obj.number == page_num %}
							<li class="active"><a>{{ page_num }} <span class="sr-only">(current)</span></a></li>
						{% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
							<li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
						{% endif %}
					{% endfor %}
				
				
					{% if page_obj.has_next %}
						<li class="icon-next"><a href="?page={{ page_obj.next_page_number }}"><i class="ion-ios-arrow-right"></i></a></li>
						<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					{% else %}
						<li class="icon-next disabled"><span><i class="ion-ios-arrow-right"></i></span></li>
					{% endif %}
				</ul>
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="sidebar">
					<div class="searh-form">
						<h4 class="sb-title">Search for TV-Show and Series</h4>
						<form class="form-style-1" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>TV-Show or Serie name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Genres & Subgenres</label>
									<div class="group-ip">
										<select
											name="skills" multiple="" class="ui fluid dropdown">
											<option value="">Enter to filter genres</option>
											<option value="Action1">Action 1</option>
					                        <option value="Action2">Action 2</option>
					                        <option value="Action3">Action 3</option>
					                        <option value="Action4">Action 4</option>
					                        <option value="Action5">Action 5</option>
										</select>
									</div>	
								</div>
								<div class="col-md-12 form-it">
									<label>Rating Range</label>
									<select>
									  <option value="range">-- Select the rating range below --</option>
									  <option value="saab">-- Select the rating range below --</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Release Year</label>
									<div class="row">
										<div class="col-md-6">
											<select>
											  <option value="range">From</option>
											  <option value="number">10</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
											  <option value="range">To</option>
											  <option value="number">20</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava1.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava2.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava3.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava4.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

television/templates/television/series_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero sr-single-hero sr-single">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1> serie listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> serie listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single movie_list">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p>Found <span>{{ series_count }} movies</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="{% url 'television:series_list' %}" class="list"><i class="ion-ios-list-outline active"></i></a>
					<a href="{% url 'television:series_grid' %}" class="grid"><i class="ion-grid"></i></a>
				</div>
			<!-- Displaying a list of TVShows with their details and cast members-->	
			{% for serie in series %}
				<div class="movie-item-style-2">
					<img src="{{ serie.image.url }}" alt="{{ serie.title }}">
					<div class="mv-item-infor">
						<h6><a href="{{ serie.get_absolute_url }}">{{ serie.title }}</a></h6>
						<p class="rate">
							<i class="ion-android-star"></i>
							<span>{{ serie.rating }}</span>/10
						</p>
						<p class="describe">{{ serie.synopsis|truncatechars_html:320 }}</p>
						<p class="run-time">
							Run Time: {{ serie.runtime }} min.
							<span>MMPA: {{ serie.mpaa_rating }}</span>
							<span>Release: {{ serie.release_year }}</span>
						</p>

                            <p>Network: <a href="#">{{ serie.network }}</a></p>
			
						<p>Stars:
							{% for cast_obj in serie.casts.all|slice:":3" %}
								{% if forloop.first %}
									<a href="{{ cast_obj.person.get_absolute_url }}">{{ cast_obj.person.name }}</a>
								{% else %}
									, <a href="{{ cast_obj.person.get_absolute_url }}">{{ cast_obj.person.name }}</a>
								{% endif %}
							{% endfor %}
						</p>
			
						<p>Status: <a href="#">{{ serie.status|capfirst }}</a></p>
					</div>
				</div>
			{% endfor %}
			<!-- End of Displaying a list of TVShows with their details and cast members-->
			

				<!-- pagination-->
				<ul class="pagination">

					{% if page_obj.has_previous %}
						<a href="?page=1">&laquo; first &nbsp; </a>
						<li class="icon-prev"><a href="?page={{ page_obj.previous_page_number }}"><i class="ion-ios-arrow-left"></i></a></li>
					{% else %}
						<li class="icon-prev disabled"><span><i class="ion-ios-arrow-left"></i></span></li>
					{% endif %}
				
					{% for page_num in page_obj.paginator.page_range %}
						{% if page_obj.number == page_num %}
							<li class="active"><a>{{ page_num }} <span class="sr-only">(current)</span></a></li>
						{% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
							<li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
						{% endif %}
					{% endfor %}
				
				
					{% if page_obj.has_next %}
						<li class="icon-next"><a href="?page={{ page_obj.next_page_number }}"><i class="ion-ios-arrow-right"></i></a></li>
						<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					{% else %}
						<li class="icon-next disabled"><span><i class="ion-ios-arrow-right"></i></span></li>

					{% endif %}
				</ul>
				<!-- end of pagination-->
				
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="sidebar">
					<div class="searh-form">
						<h4 class="sb-title">Search for TV-Show and Series</h4>
						<form class="form-style-1" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>TV-Show or Serie name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Genres & Subgenres</label>
									<div class="group-ip">
										<select
											name="skills" multiple="" class="ui fluid dropdown">
											<option value="">Enter to filter genres</option>
											<option value="Action1">Action 1</option>
					                        <option value="Action2">Action 2</option>
					                        <option value="Action3">Action 3</option>
					                        <option value="Action4">Action 4</option>
					                        <option value="Action5">Action 5</option>
										</select>
									</div>
									
								</div>
								<div class="col-md-12 form-it">
									<label>Rating Range</label>
									
									 <select>
										<option value="range">-- Select the rating range below --</option>
										<option value="saab">-- Select the rating range below --</option>
										<option value="saab">-- Select the rating range below --</option>
										<option value="saab">-- Select the rating range below --</option>
									</select>
									
								</div>
								<div class="col-md-12 form-it">
									<label>Release Year</label>
									<div class="row">
										<div class="col-md-6">
											<select>
												<option value="range">From</option>
												<option value="number">10</option>
												<option value="number">20</option>
												<option value="number">30</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
												<option value="range">To</option>
												<option value="number">20</option>
												<option value="number">30</option>
												<option value="number">40</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava1.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava2.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava3.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="{% static 'images/uploads/ava4.jpg' %}" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}