BluckBuster/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('user/', include('account.urls', namespace='account')),
    path('movies/', include('cinema.urls', namespace='cinema')),
    path('series/', include('television.urls', namespace='television')),
    path('celebs/', include('people.urls', namespace='people')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'blog.views.custom_404_view'

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change_avatar/', views.ChangeProfilePictureView.as_view(), name='change_profile_picture'),
    path('favorites/movies/', views.FavoriteMovieListView.as_view(), name='favorite_movies'),
    path('favorites/movies/edit/', views.FavoriteMovieEditView.as_view(), name='favorite_movies_edit'),
    path('favorite/movies/delete/<int:movie_id>/', views.FavoriteMovieDeleteView.as_view(), name='delete_favorite_movie'),
    path('favorites/series/', views.FavoriteTVShowListView.as_view(), name='favorite_series'),
    path('favorites/series/edit/', views.FavoriteTVShowEditView.as_view(), name='favorite_series_edit'),
    path('favorite/series/delete/<int:tvshow_id>/', views.FavoriteTVShowDeleteView.as_view(), name='delete_favorite_serie'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('reset_password/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset_password/confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('signup/', views.UserRegisterView.as_view(), name='signup'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('blogs/', views.BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
]    

cinema/urls.py
from django.urls import path
from . import views

app_name = 'cinema'

urlpatterns = [
    path('', views.MovieListView.as_view(), name='movies_list'),
    path('grid/', views.MovieGridView.as_view(), name='movies_grid'),
    path('<int:pk>/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('<int:pk>/', views.MovieDetailView.as_view(), name='movie_detail_by_id'),
    path('search_results/', views.SearchMoviesView.as_view(), name='search_results'),
    path('favorite_movies/add/', views.FavoriteMovieCreateView.as_view(), name='favorite_movie_create'),
]

people/urls.py
from django.urls import path
from . import views

app_name = 'people'

urlpatterns = [
    path('', views.CelebListView.as_view(), name='celeb_list'),
    path('<int:pk>/', views.CelebDetailView.as_view(), name='celeb_detail'),
    path('grid/', views.CelebGridView.as_view(), name='celeb_grid'),
]

television/urls.py
from django.urls import path
from . import views

app_name = 'television'

urlpatterns = [
    path('', views.SerieListView.as_view(), name='series_list'),
    path('grid/', views.SerieGridView.as_view(), name='series_grid'),
    path('<int:pk>/<slug:slug>/', views.SerieDetailView.as_view(), name='serie_detail'),
    path('<int:pk>/', views.SerieDetailView.as_view(), name='serie_detail_by_id'),
    path('favorite_series/add/', views.FavoriteTVShowCreateView.as_view(), name='favorite_serie_create')
]

templates/inc/footer.html
{% load static %}

<!-- footer section-->
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href="{% url 'blog:home' %}"><img class="logo" src="{% static 'images/logo1.png' %}" alt=""></a>
				 <p>5th Avenue st.<br>
				Tehran, Tehranpars</p>
				<p>Call us: <a href="callto:(+98)9381471959">(+98) 938 147 1959</a></p>
			</div>
			<div class="flex-child-ft item2">
				<h4>Resources</h4>
				<ul>
					<li><a href="{% url 'blog:about' %}">About</a></li> 
					<li><a href="{% url 'blog:about' %}">Blockbuster</a></li>
					<li><a href="{% url 'blog:about' %}">Contact Us</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Account</h4>
				<ul>
                    {% if request.user.is_authenticated %}
                        <li class="btn"  ><a  href="{% url 'account:profile' %}">My Account</a></li>
                        <li><a href="#">My Watchlist</a></li>	
                        <li><a href="{% url 'account:favorite_movies' %}">My Favorites</a></li>
                    {% else%}
                        <li class="loginLink"><a href="#">Login</a></li>
                        <li class="btn signupLink"><a href="#">SignUp</a></li>
                    {% endif %}   
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Newsletter</h4>
				<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
				<form action="#">
					<input type="text" placeholder="Enter your email...">
				</form>
				<a href="#" class="btn">Subscribe now <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
	<div class="ft-copyright">
		<div class="ft-left">
			<p><a target="_blank" href="#">Templates Hub</a></p>
		</div>
		<div class="backtotop">
			<p><a href="#" id="back-to-top">Back to top  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>
<!-- end of footer section-->

templates/inc/header.html
{% load static %}

<!--signup form popup-->
<div class="login-wrapper"  id="signup-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
        <h3>sign up</h3>
        <form method="post" action="{% url 'account:signup' %}">
            {% csrf_token %}
            <div class="row">
                 <label for="username-2">
                    Username:
                    <input type="text" name="username" id="username-2" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{8,20}$" required="required" />
                </label>
            </div>
           
            <div class="row">
                <label for="email-2">
                    your email:
                    <input type="text" name="email" id="email-2" required="required" />
                </label>
            </div>
             <div class="row">
                <label for="password-2">
                    Password:
                    <input type="password" name="password1" id="password-2" required="required" />
                </label>
            </div>
             <div class="row">
                <label for="repassword-2">
                    re-type Password:
                    <input type="password" name="password2" id="repassword-2"  required="required" />
                </label>
            </div>
           <div class="row">
             <button type="submit">sign up</button>
           </div>
        </form>
    </div>
</div>
<!--end of signup form popup-->

<!--login form popup-->
<div class="login-wrapper" id="login-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
        <h3>Login</h3>
        <form method="post" action="{% url 'account:login' %}">
            {% csrf_token %}
        	<div class="row">
        		 <label for="username">
                    Username:
                    <input type="text" name="username" id="username" required="required" />
                </label>
        	</div>
           
            <div class="row">
            	<label for="password">
                    Password:
                    <input type="password" name="password" id="password"  required="required" />
                </label>
            </div>
            <div class="row">
            	<div class="remember">
					<div>
						<input type="checkbox" name="remember" value="Remember me"><span>Remember me</span>
					</div>
            		<a href="{% url 'account:reset_password' %}">Forget password ?</a>
            	</div>
            </div>
           <div class="row">
           	 <button type="submit">Login</button>
           </div>
        </form>
        <div class="row">
        	<p>Or via social</p>
            <div class="social-btn-2">
            	<a class="fb" href="#"><i class="ion-social-facebook"></i>Facebook</a>
            	<a class="tw" href="#"><i class="ion-social-twitter"></i>twitter</a>
            </div>
        </div>
    </div>
</div>
<!--end of login form popup-->


<!-- BEGIN | Header -->
<header class="ht-header">
	<div class="container">
		<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
				    <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					    <span class="sr-only">Toggle navigation</span>
					    <div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
				    </div>
				    <a href="{% url 'blog:home' %}"><img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58"></a>
			    </div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						<li><a href="{% url 'blog:home' %}">Home</a></li>
						<li><a href="{% url 'cinema:movies_list' %}">Movies</a></li>
						<li><a href="{% url 'television:series_list' %}">TV SHows</a></li>
						<li><a href="{% url 'people:celeb_list' %}">Celebs</a></li>
						<li><a href="{% url 'blog:blog_list' %}">News</a></li>
						<li><a href="{% url 'blog:about' %}">About Us</a></li>  
					</ul>
					<ul class="nav navbar-nav flex-child-menu menu-right">           
						<li><a href="{% url 'admin:index' %}">Admin</a></li>
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'account:logout' %}">Logout</a></li>
                            <li class="btn"  ><a  href="{% url 'account:profile' %}">{{user.username}}</a></li>
                        {% else%}
    						<li class="loginLink"><a href="#">LOG In</a></li>
    						<li class="btn signupLink"><a href="#">sign up</a></li>
                        {% endif %}    
					</ul>
				</div>
			<!-- /.navbar-collapse -->
	    </nav>
	    
	    <!-- top search form -->
            <form class="top-search" method="POST" action="{% url 'cinema:search_results' %}">
                {% csrf_token %}
                <select name="media_type">
                    <option value="all" {% if media_type == 'all' %}selected{% endif %}>All</option>
                    <option value="movies" {% if media_type == 'movies' %}selected{% endif %}>Movies</option>
                    <option value="series" {% if media_type == 'series' %}selected{% endif %}>TV Shows</option>
                    <option value="celebs" {% if media_type == 'celebs' %}selected{% endif %}>Celebrities</option>
                 </select>
                <input class="form-control me-2" type="search" placeholder="Search for a movie, TV Show or celebrity that you are looking for..." aria-label="Search" name="searched" required>
                <!-- <button class="top-search redbtn" type="submit">Search</button> -->
            </form>
          
            <br>
            {% include 'inc/messages.html' %}
	</div>
</header>
<!-- END | Header -->

templates/inc/messages.html
{% if messages %}
<style>
    .cool-shape-container {
      display: flex;
      justify-content: center;
    }
  
    .cool-shape {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 10px;
      background-color: #f0f0f0;
      border-radius: 10px;
      width: 400px;
      font-size: 16px;
    }
  
    .cool-shape:before {
      content: "";
      position: absolute;
      top: -10px;
      left: 50%;
      transform: translateX(-50%);
      border: 10px solid transparent;
      border-bottom-color: #f0f0f0;
    }
  </style>

  
{% for msg in messages %}
    <div class="cool-shape-container">
        <strong class="alert alert-{{ msg.tags }} cool-shape">
          {{ msg }}
        </strong>
    </div>
{% endfor %}
{% endif %}


  